# Generated by Django 4.2.17 on 2026-03-18 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('REGISTER', 'User Registered'), ('BORROW', 'Book Borrowed'), ('RETURN', 'Book Returned'), ('ADD_BOOK', 'Book Added'), ('EDIT_BOOK', 'Book Edited'), ('DELETE_BOOK', 'Book Deleted'), ('ADD_USER', 'User Added'), ('EDIT_USER', 'User Edited'), ('DELETE_USER', 'User Deleted'), ('EXPORT', 'Report Exported'), ('BACKUP', 'Data Backup'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
